name: Run tests

on:
    push:
      branches: [ "github_workflow" ]
    pull_request:
      branches: [ "github_workflow" ]

permissions:
    contents: read

jobs:
    run-tests:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          java-version: ['8', '11', '17']
      name: Run tests with java SDK ${{ matrix.java-version }}

      steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies
        run: |
          pip install --user codecov

      - name: Check JAVA version (v${{ matrix.java-version }})
        run: java -version

      - name: Run tests
        # Fail on first error
        run: |
          set -e
          mvn test

      - name: Upload coverage reports to Codecov
        run: codecov